import = ["/home/alex/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = false

[colors]
transparent_background_colors = true

[cursor]
vi_mode_style = "Block"

[cursor.style]
blinking = "On"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 9.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Shift|Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 8

[shell]
program = "/usr/bin/fish"

[window]
decorations = "none"
opacity = 0.8
