import:
  # - ~/.config/alacritty/kanagawa.yml
  # - ~/.config/alacritty/tokyonight_night.yml
  # - ~/.config/alacritty/tokyonight_moon.yml
  # - ~/.config/alacritty/tokyonight_storm.yml
  # - ~/.config/alacritty/tokyonight_day.yml
  - ~/.config/alacritty/catppuccin-mocha.yml
  # - ~/.config/alacritty/catppuccin-macchiato.yml
  # - ~/.config/alacritty/catppuccin-frappe.yml
  # - ~/.config/alacritty/catppuccin-latte.yml

env:
  TERM: xterm-256color

window:
  decorations: none
  opacity: 0.95

scrolling:
  history: 10000
  multiplier: 8

font:
  normal:
    family: Iosevka Term SS14
    style: Regular

  bold:
    family: Iosevka Term SS14
    style: Bold

  italic:
    family: Iosevka Term SS14
    style: Italic

  bold_italic:
    family: Iosevka Term SS14
    style: Bold Italic

colors:
  transparent_background_colors: true

cursor:
  style:
    shape: Underline
    blinking: Off
  vi_mode_style: None

live_config_reload: false

shell:
  program: /usr/bin/zsh

mouse:
  hide_when_typing: true
