tokyo-night: &tokyo-night
  primary:
    background: '#1a1b26'
    foreground: '#c0caf5'

  normal:
    black:   '#15161e'
    red:     '#f7768e'
    green:   '#9ece6a'
    yellow:  '#e0af68'
    blue:    '#7aa2f7'
    magenta: '#bb9af7'
    cyan:    '#7dcfff'
    white:   '#a9b1d6'

  bright:
    black:   '#414868'
    red:     '#f7768e'
    green:   '#9ece6a'
    yellow:  '#e0af68'
    blue:    '#7aa2f7'
    magenta: '#bb9af7'
    cyan:    '#7dcfff'
    white:   '#c0caf5'

  indexed_colors:
    - { index: 16, color: '#ff9e64' }
    - { index: 17, color: '#db4b4b' }

tokyo-storm: &tokyo-storm
  primary:
    background: '#24283b'
    foreground: '#c0caf5'

  normal:
    black:   '#1d202f'
    red:     '#f7768e'
    green:   '#9ece6a'
    yellow:  '#e0af68'
    blue:    '#7aa2f7'
    magenta: '#bb9af7'
    cyan:    '#7dcfff'
    white:   '#a9b1d6'

  bright:
    black:   '#414868'
    red:     '#f7768e'
    green:   '#9ece6a'
    yellow:  '#e0af68'
    blue:    '#7aa2f7'
    magenta: '#bb9af7'
    cyan:    '#7dcfff'
    white:   '#c0caf5'

  indexed_colors:
    - { index: 16, color: '#ff9e64' }
    - { index: 17, color: '#db4b4b' }

tokyo-light: &tokyo-light
  primary:
    background: '#e1e2e7'
    foreground: '#3760bf'

  normal:
    black:   '#e9e9ed'
    red:     '#f52a65'
    green:   '#587539'
    yellow:  '#8c6c3e'
    blue:    '#2e7de9'
    magenta: '#9854f1'
    cyan:    '#007197'
    white:   '#6172b0'

  bright:
    black:   '#a1a6c5'
    red:     '#f52a65'
    green:   '#587539'
    yellow:  '#8c6c3e'
    blue:    '#2e7de9'
    magenta: '#9854f1'
    cyan:    '#007197'
    white:   '#3760bf'

  indexed_colors:
    - { index: 16, color: '#b15c00' }
    - { index: 17, color: '#c64343' }

kanagawa: &kanagawa
  primary:
    background: '#1f1f28'
    foreground: '#dcd7ba'

  normal:
    black:   '#090618'
    red:     '#c34043'
    green:   '#76946a'
    yellow:  '#c0a36e'
    blue:    '#7e9cd8'
    magenta: '#957fb8'
    cyan:    '#6a9589'
    white:   '#c8c093'

  bright:
    black:   '#727169'
    red:     '#e82424'
    green:   '#98bb6c'
    yellow:  '#e6c384'
    blue:    '#7fb4ca'
    magenta: '#938aa9'
    cyan:    '#7aa89f'
    white:   '#dcd7ba'

  selection:
    background: '#2d4f67'
    foreground: '#c8c093'

  indexed_colors:
    - { index: 16, color: '#ffa066' }
    - { index: 17, color: '#ff5d62' }

colors: *tokyo-night
