format = """
 $username\
$hostname\
$directory\
$git_branch\
$git_status\
$rust\
$lua\
\n\
$character"""

right_format = """
$jobs\
$cmd_duration\
$status"""

[username]
format = '[$user]($style) '

[hostname]
format = '[\[$ssh_symbol$hostname\]]($style) '

[directory]
format = '[$path]($style)( [$read_only]($read_only_style)) '
truncation_length = 10

[git_branch]
format = '[\[$symbol$branch(:$remote_branch)\]]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style)) '
conflicted = '='
ahead = '⇡'
behind = '⇣'
diverged = '⇕'
up_to_date = ''
untracked = '?'
stashed = '$'
modified = '!'
staged = '+'
renamed = '»'
deleted = '✘'

[rust]
format = '[\[$symbol($toolchain)\]]($style) '

[lua]
format = '[\[$symbol\]]($style) '

[character]
format = " $symbol "
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold green)"
vimcmd_replace_one_symbol = "[<](bold purple)"
vimcmd_replace_symbol = "[<](bold purple)"
vimcmd_visual_symbol = "[<](bold yellow)"


[jobs]
format = "[$symbol$number](bold yellow) "

[cmd_duration]
format = "[$duration](bold yellow) "

[status]
disabled = false
format = '[$status]($style)'
