[manager]
prepend_keymap = [
    { on = [ "g", "c" ], run = "cd ~/.config",              desc = ".config" },
    { on = [ "g", "l" ], run = "cd ~/.local",               desc = ".local" },
    { on = [ "g", "t" ], run = "cd /tmp",                   desc = "tmp" },
    { on = [ "g", "e" ], run = "cd /run/media/$USER",       desc = "external devices" },
    { on = [ "g", "T" ], run = "cd ~/.local/share/Trash",   desc = "trash" },

    { on = [ "<C-s>" ], run  = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
    { on = [ "<C-n>" ], run = '''shell 'dragon-drop -x -T "$0"' --confirm''', desc = "Open drag-n-drop" },
]

