[manager]
prepend_keymap = [
    { on = [ "g", "h" ], run = "cd ~",                      desc = "home" },
    { on = [ "g", "c" ], run = "cd ~/.config",              desc = ".config" },
    { on = [ "g", "l" ], run = "cd ~/.local",               desc = ".local" },
    { on = [ "g", "d" ], run = "cd ~/Downloads",            desc = "Downloads" },
    { on = [ "g", "t" ], run = "cd /tmp",                   desc = "tmp" },
    { on = [ "g", "e" ], run = "cd /run/media/$USER",       desc = "external devices" },
    { on = [ "g", "T" ], run = "cd ~/.local/share/Trash",   desc = "trash" },

    { on = [ "-" ], run = '''shell 'ln -s "$0" "$0".l' --confirm''', desc = "Symlink the absolute path of files" },
    { on = [ "_" ], run = '''shell 'ln -sr "$0" "$0".l' --confirm''', desc = "Symlink the relative path of files" },

    { on = [ "<C-s>" ], run  = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
    { on = [ "<C-n>" ], run = '''shell 'dragon-drop -x -T "$0"' --confirm''', desc = "Open drag-n-drop" },
]

